### ISSUE TITLE
Discussion: Should OperationCollection.add(null) throw?

### ISSUE THREAD

**Issue by gmcelhoe** [vmware/test-operations#13]
Currently, if you add a "null" operation, then the test will fail because the add() method throws a NullPointerException.

I'm thinking the library would be more useful if "null" operations were simply ignored.  It would make more readable tests that conditionally added operations

Before:
```java
 op = createMyNewOperation();
 if (op != null) {
   opList.add(op);
 }
```

After:
```java
 opList.add(createMyNewOperation());
```

**Comment by sbhandari** [comment]
Sure, I am just curious when do you create NULL operation? Is it some sort of factory creating operations and for unsupported case it is returned as NULL?

**Comment by gmcelhoe** [comment]
The specific instance is a method that returns a create operation (for networks) that doesn't need to be done if there is no suitable configuration.

The bigger concept is based on the reading I have done recently, especially the Ousterhout book about Software Design, around making APIs with fewer error states.  If the caller wants to check for null, great, but the API is stronger if it deals with null operations as "null" or "do nothing", instead of suspecting that the caller didn't know the result was null.

According to that logic, OperationCollection.add(null) is an easy choice.  I wonder if you have noticed other places in the API where the same logic would apply.
