### ISSUE TITLE
Operation added in operation sequence is not executing revert validator

### ISSUE THREAD

**Issue by sbhandari** [vmware/test-operations#6]
Test Class: [https://github.com/vmware/test-operations/blob/master/test-operations/src/test/java/com/vmware/operations/ValidatorTests.java]

```
@Test
    public final void testOneSyncValidatorWithSequence() throws Exception {
        AtomicInteger opCount = new AtomicInteger();
        AtomicInteger validationCount = new AtomicInteger();

        try (OperationSequence ops = Operations.sequence()) {
            IncrementOperation op = new IncrementOperation(opCount);
            op.addValidator(new IncrementSyncValidator(validationCount));
            ops.addExecute(op);
        }
        
         /* Fails as the revert validator is not executed. */
        Assert.assertEquals("operation count should match", 0, opCount.get());
        Assert.assertEquals("validation count should match", 0, validationCount.get());
    }
```

**Comment by gmcelhoe** [comment]
I think that the current behavior is the best default for validator cleanup.

See the recent commit, but here is what I am proposing:

If an operation is executed, the validateExecutionAsync will be called.  Now the validator is guaranteed that one more method will be called -- if revert succeeds, then validateRevertAsync will be called, but if revert fails, then validateCleanupAsync will be called instead.

Will that work for your use case?

**Comment by sbhandari** [comment]
Yes that should work Glenn. Did you release new version for 0.9.6 in sonatype?

**Comment by gmcelhoe** [comment]
I'll do a version upgrade shortly

**Comment by sbhandari** [comment]
will this be 0.9.6 or 0.9.7, just curious?
